### ISSUE TITLE
How to configure indent size

### ISSUE THREAD

**Issue by wiz21b** [wendelscardua/ca65-mode#5]
Hello,
Tried to use your package today. Looks nice but I don't like the default indent size of 2. 
Is it possible to change that ? I didn't see anything related to configuration... Just a setq-local in your code...
Could you make that available as a configuration option ?
thx,stF

**Comment by wendelscardua** [comment]
I guess I could simply remove that setq-local so people can use their preferred indent size - I don't remember why I've put that there, but if removing the setq-local ends up breaking something I'll add a configurable option instead.
